config/routes.rb
TiagoBelemV2::Application.routes.draw do
  get "endorsees/home"
  get "bios/home"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :galleries

  resources :photos

  resources :events

  resources :contacts
  
  resources :midia

  resources :musics

  resources :supports

  get "welcome/index"
  
  resources :movies

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base

validates :name, :email, :message, presence: true 

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos
	validates_presence_of :name, :content
	validates_length_of :content, maximum: 255
	validates_length_of :name, maximum: 50
end

app/models/movie.rb
class Movie < ActiveRecord::Base
auto_html_for :link do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/music.rb
class Music < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :gallery
	validates_presence_of :image, :gallery_id
	mount_uploader :image, ImageUploader
	
end

app/models/support.rb
class Support < ActiveRecord::Base
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  def home
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @jan = []
    @fev = []
    @mar = []
    @abr = []
    @mai = []
    @jun = []
    @jul = []
    @ago = []
    @set = []
    @out = []
    @nov = []
    @dez = []
    unless @events.empty?
      for event in @events do
        if event.event_date.strftime("%B") == "January"
          @jan << event
        elsif event.event_date.strftime("%B") == "February"
          @fev << event
        elsif event.event_date.strftime("%B") == "March"
          @mar << event
        elsif event.event_date.strftime("%B") == "April"
          @abr << event
        elsif event.event_date.strftime("%B") == "May"
          @mai << event
        elsif event.event_date.strftime("%B") == "June"
          @jun << event
        elsif event.event_date.strftime("%B") == "July"
          @jul << event
        elsif event.event_date.strftime("%B") == "August"
          @ago << event
        elsif event.event_date.strftime("%B") == "September"
          @set << event
        elsif event.event_date.strftime("%B") == "October"
          @out << event
        elsif event.event_date.strftime("%B") == "November"
          @nov << event
        elsif event.event_date.strftime("%B") == "December"        
          @dez << event
        end
      end
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_date, :time, :name, :place, :more_information)
    end
end

app/controllers/midia_controller.rb
class MidiaController < ApplicationController
	def index
		@galleries = Gallery.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, hard_wrap: :true, filter_html: :true, autolink: :true, no_intraemphasis: :true, fenced_code: :true, gh_blockcode: :true)
  
  return markdown.render(text).html_safe
end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/endorsees_helper.rb
module EndorseesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def event_dateform(date)
		date.strftime("%d/%m/%Y")
	end

	def form_hora(date)
		date.strftime("%I:%MH")
	end

end

app/helpers/galleries_helper.rb
module GalleriesHelper
	
end

app/helpers/midia_helper.rb
module MidiaHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<div class="container">
<div class="row">
    <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div>
      <%= f.label :event_date %><br>
      <%= f.date_select :event_date %>
    </div>
    <div>
      <%= f.label :time %><br>
      <%= f.datetime_select :time %>
    </div>
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :place %><br>
      <%= f.text_field :place %>
    </div>
    <div>
      <%= f.label :more_information %><br>
      <%= f.text_field :more_information %>
    </div>
    <div class="actions">
    <br>
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-offset-7 col-md-5">
      <% unless @jan.empty? %>
      <h3 id="azulclaro">JANEIRO</h3>
      
      <% @jan.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @fev.empty? %>
      <h3 id="azulclaro">FEVEREIRO</h3>
      <% @fev.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @mar.empty? %>
      <h3 id="azulclaro">MARÇO</h3>
      <% @mar.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @abr.empty? %>
      <h3 id="azulclaro">ABRIL</h3>
      <% @abr.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @mai.empty? %>
      <h3 id="azulclaro">MAIO</h3>
      <% @mai.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
      <br>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @jun.empty? %>
      <h3 id="azulclaro">JUNHO</h3>
      <% @jun.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
      
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @jul.empty? %>
      <h3 id="azulclaro">JULHO</h3>
      <% @jul.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @ago.empty? %>
      <h3 id="azulclaro">AGOSTO</h3>
      <% @ago.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @ago.empty? %>
      <h3 id="azulclaro">SETEMBRO</h3>
      <% @set.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>

      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @ago.empty? %>
      <h3 id="azulclaro">OUTUBRO</h3>
      <% @out.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>
      </strong>
      <br>
      <% end %>
      <% end %>
      
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @nov.empty? %>
      <h3 id="azulclaro">NOVEMBRO</h3>
      <% @nov.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>
      </strong>
      <br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-offset-7 col-md-5">
      <% unless @dez.empty? %>
      <h3 id="azulclaro">DEZEMBRO</h3>
      <% @dez.each do |event| %>
      <strong>
        <p class="deixarosa"><%= event_dateform (event.event_date) %>-</p>
        <p class="deixaazul"><%= event.name %></p>
        <p class="deixarosa">//</p>
        <div class="deixaazul">
          <%= form_hora event.time %>
        </div>
        <div class="deixarosa">
          //
        </div>
        <div class="deixaazul">
          <%= event.place %>
        </div>
        <p class="deixaazulclaro">
          (<%= event.more_information %>)
        </p>
      </strong>
      <br>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
	<h1>Novo Evento</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>