config/routes.rb
TiagoBelemV2::Application.routes.draw do
  get "endorsees/home"
  get "bios/home"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :galleries

  resources :photos

  resources :events

  resources :contacts
  
  resources :midia

  resources :musics

  resources :supports

  get "welcome/index"
  
  resources :movies

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base

validates :name, :email, :message, presence: true 

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos
	validates_presence_of :name, :content
	validates_length_of :content, maximum: 255
	validates_length_of :name, maximum: 50
end

app/models/movie.rb
class Movie < ActiveRecord::Base
auto_html_for :link do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/music.rb
class Music < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :gallery
	validates_presence_of :image, :gallery_id
	mount_uploader :image, ImageUploader
	
end

app/models/support.rb
class Support < ActiveRecord::Base
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  def home
  end
end

app/controllers/midia_controller.rb
class MidiaController < ApplicationController
	def index
		@galleries = Gallery.all
	end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :set_support, only: [:show, :edit, :update, :destroy]

  # GET /supports
  # GET /supports.json
  def index
    @supports = Support.all
  end

  # GET /supports/1
  # GET /supports/1.json
  def show
  end

  # GET /supports/new
  def new
    @support = Support.new
  end

  # GET /supports/1/edit
  def edit
  end

  # POST /supports
  # POST /supports.json
  def create
    @support = Support.new(support_params)

    respond_to do |format|
      if @support.save
        format.html { redirect_to @support, notice: 'Support was successfully created.' }
        format.json { render action: 'show', status: :created, location: @support }
      else
        format.html { render action: 'new' }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supports/1
  # PATCH/PUT /supports/1.json
  def update
    respond_to do |format|
      if @support.update(support_params)
        format.html { redirect_to @support, notice: 'Support was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1
  # DELETE /supports/1.json
  def destroy
    @support.destroy
    respond_to do |format|
      format.html { redirect_to supports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support
      @support = Support.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def support_params
      params.require(:support).permit(:link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, hard_wrap: :true, filter_html: :true, autolink: :true, no_intraemphasis: :true, fenced_code: :true, gh_blockcode: :true)
  
  return markdown.render(text).html_safe
end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/endorsees_helper.rb
module EndorseesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def event_dateform(date)
		date.strftime("%d/%m/%Y")
	end

	def form_hora(date)
		date.strftime("%I:%MH")
	end

end

app/helpers/galleries_helper.rb
module GalleriesHelper
	
end

app/helpers/midia_helper.rb
module MidiaHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/supports/_form.html.erb
<%= form_for(@support) do |f| %>
  <% if @support.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@support.errors.count, "error") %> prohibited this support from being saved:</h2>

      <ul>
      <% @support.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supports/edit.html.erb
<h1>Editing support</h1>

<%= render 'form' %>

<%= link_to 'Show', @support %> |
<%= link_to 'Back', supports_path %>

app/views/supports/index.html.erb
<h1>Listing supports</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @supports.each do |support| %>
      <tr>
        <td><%= support.link %></td>
        <td><%= link_to 'Show', support %></td>
        <td><%= link_to 'Edit', edit_support_path(support) %></td>
        <td><%= link_to 'Destroy', support, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Support', new_support_path %>

app/views/supports/new.html.erb
<h1>New support</h1>

<%= render 'form' %>

<%= link_to 'Back', supports_path %>

app/views/supports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @support.link %>
</p>

<%= link_to 'Edit', edit_support_path(@support) %> |
<%= link_to 'Back', supports_path %>