config/routes.rb
TiagoBelemV2::Application.routes.draw do
  get "endorsees/home"
  get "bios/home"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :galleries

  resources :photos

  resources :events

  resources :contacts
  
  resources :midia

  resources :musics

  resources :supports

  get "welcome/index"
  
  resources :movies

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base

validates :name, :email, :message, presence: true 

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos
	validates_presence_of :name, :content
	validates_length_of :content, maximum: 255
	validates_length_of :name, maximum: 50
end

app/models/movie.rb
class Movie < ActiveRecord::Base
auto_html_for :link do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/music.rb
class Music < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :gallery
	validates_presence_of :image, :gallery_id
	mount_uploader :image, ImageUploader
	
end

app/models/support.rb
class Support < ActiveRecord::Base
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  def home
  end
end

app/controllers/midia_controller.rb
class MidiaController < ApplicationController
	def index
		@galleries = Gallery.all
	end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render action: 'show', status: :created, location: @music }
      else
        format.html { render action: 'new' }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, hard_wrap: :true, filter_html: :true, autolink: :true, no_intraemphasis: :true, fenced_code: :true, gh_blockcode: :true)
  
  return markdown.render(text).html_safe
end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/endorsees_helper.rb
module EndorseesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def event_dateform(date)
		date.strftime("%d/%m/%Y")
	end

	def form_hora(date)
		date.strftime("%I:%MH")
	end

end

app/helpers/galleries_helper.rb
module GalleriesHelper
	
end

app/helpers/midia_helper.rb
module MidiaHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/musics/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@music) do |f| %>
    <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
    <%= f.label :link, class: "mudatexto" %><br>
      <%= f.text_area :link, placeholder: "Cole o link do soundcloud aqui", :rows => 2, :cols => 63 %>
    </div>
    <div class="actions">
      <br>
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <% end %>

  </div>
</div>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <% @musics.each do |music| %>
    <object height="18" width="100%"><td><%= raw (music.link)%></td></object>
    <br>
    <br>
    <% end %>
  </div>
</div>

app/views/musics/new.html.erb
<div class="container">
	<div class="row">
	<h1 class="mudatexto">New music</h1>

	<%= render 'form' %>

	</div>
</div>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= raw @music.link %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>